require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
AllCops:
  Exlude:
    - 'bin/bundle'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Metrics/BlockLength:
  Max: 47

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 9

Layout/LineLength:
  Max: 198

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'

RSpec/FilePath:
  Exclude:
    - 'spec/rspec_methods_spec.rb'
    - 'spec/subject_described_class_spec.rb'

RSpec/ExpectActual:
  Enabled: false

Rails/FilePath:
  Enabled: false







